/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemesananmakanan1;

import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author Abe Dhe
 */
public class HalamanDepan extends javax.swing.JFrame {
    int waktumulai = 0;
    /**
     * Creates new form HalamanDepan
     */
    public HalamanDepan() {
        initComponents();
        new Thread(){
            public void run(){
                while(true){
                    Calendar kalender = new GregorianCalendar();
                    int jam = kalender.get(Calendar.HOUR_OF_DAY);
                    int menit = kalender.get(Calendar.MINUTE);
                    int detik = kalender.get(Calendar.SECOND);
                    
                    int date = kalender.get(Calendar.DAY_OF_MONTH);
                    int month = kalender.get(Calendar.MONTH)+1;
                    int year = kalender.get(Calendar.YEAR);
                    String time = jam + " : " + menit + " : " + detik;
                    tampilan_Kalender.setText(date + " - " + month + " - " + year);
                    tampilan_Jam.setText(time);
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tombol_PesanSekarang = new javax.swing.JButton();
        SelamatDatang = new javax.swing.JLabel();
        Namawarung = new javax.swing.JLabel();
        tampilan_Jam = new javax.swing.JLabel();
        tampilan_Kalender = new javax.swing.JLabel();
        identitas = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tombol_PesanSekarang.setBackground(new java.awt.Color(255, 255, 255));
        tombol_PesanSekarang.setFont(new java.awt.Font("Century", 0, 20)); // NOI18N
        tombol_PesanSekarang.setText("Pesan Sekarang!");
        tombol_PesanSekarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_PesanSekarangActionPerformed(evt);
            }
        });
        getContentPane().add(tombol_PesanSekarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 250, 60));

        SelamatDatang.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 40)); // NOI18N
        SelamatDatang.setText("Selamat Datang di Warung Makan");
        getContentPane().add(SelamatDatang, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 800, 70));

        Namawarung.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 55)); // NOI18N
        Namawarung.setText("\"WONG BOEMENT\"");
        getContentPane().add(Namawarung, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 630, 110));

        tampilan_Jam.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        tampilan_Jam.setText("Jam");
        getContentPane().add(tampilan_Jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 250, 30));

        tampilan_Kalender.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        tampilan_Kalender.setText("Kalender");
        getContentPane().add(tampilan_Kalender, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 250, 30));

        identitas.setFont(new java.awt.Font("Segoe UI Symbol", 0, 10)); // NOI18N
        identitas.setText("Designed By : Fiqri Abdilah (21120117130061)");
        getContentPane().add(identitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 200, 30));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemesananmakanan1/03-indomie telur.jpeg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombol_PesanSekarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_PesanSekarangActionPerformed
        form_Pemesanan n = new form_Pemesanan();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombol_PesanSekarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanDepan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanDepan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanDepan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanDepan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanDepan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Namawarung;
    private javax.swing.JLabel SelamatDatang;
    private javax.swing.JLabel identitas;
    private javax.swing.JLabel tampilan_Jam;
    private javax.swing.JLabel tampilan_Kalender;
    private javax.swing.JButton tombol_PesanSekarang;
    // End of variables declaration//GEN-END:variables
}